Std 35
Ebasheriki/StudySharp pull request #32
Opened 2021-09-23 22:47 UTC by Evenya

Ebis ono vse konem nada Meeting srochna

2021-09-24 09:04 UTC, zefirlover requested changes, later dismissed
Change the name of the pull request. Pattern: STD-N | Name. (Copy it from Trello)

2021-09-24 09:04 UTC, zefirlover commented on server/StudySharp.ApplicationServices/Commands/AddTheoryBlockCommand.cs
> +    public sealed class AddTheoryBlockHandler : IRequestHandler<AddTheoryBlockCommand, OperationResult>
Change AddTheoryBlockHandler to AddTheoryBlockCommandHandler due to our name conventions

2021-09-24 09:04 UTC, zefirlover commented on server/StudySharp.ApplicationServices/Commands/AddTheoryBlockCommand.cs
> +        public AddTheoryBlockHandler(StudySharpDbContext sharpDbContext)
AddTheoryBlockCommandHandler

2021-09-24 09:04 UTC, zefirlover commented on server/StudySharp.ApplicationServices/Commands/AddTheoryBlockCommand.cs
> +            if (await _context.TheoryBlocks.AnyAsync(c => Equals(c.Name.ToLower()) && c.CourseId == request.CourseId, cancellationToken))
Change "c" to "_" due to our name conventions. AddCourseCommand.cs variant isn't correct

2021-09-24 09:04 UTC, zefirlover commented on server/StudySharp.ApplicationServices/Commands/AddTheoryBlockCommand.cs
> +            if (await _context.TheoryBlocks.AnyAsync(c => Equals(c.Name.ToLower()) && c.CourseId == request.CourseId, cancellationToken))
Where is request.Name.ToLower()?

2021-09-24 09:04 UTC, zefirlover commented on server/StudySharp.ApplicationServices/Commands/AddTheoryBlockCommand.cs
> +            await _context.SaveChangesAsync(cancellationToken);
I think we need here an extra enter here, what do you think @KolaCation?

2021-09-24 09:04 UTC, zefirlover commented on server/StudySharp.ApplicationServices/Commands/AddTheoryBlockCommand.cs
> +using StudySharp.Domain.Constants;
Are we really need here "System.Linq" and "Microsoft.VisualBasic" usings?

2021-09-24 09:04 UTC, zefirlover commented on server/StudySharp.ApplicationServices/Commands/RemoveTheoryBlockByIdCommand.cs
> +            CancellationToken cancellationToken)
It's better to write that in one row

2021-09-24 09:04 UTC, zefirlover commented on server/StudySharp.ApplicationServices/Queries/GetTheoryBlockByIdQuery.cs
> +    // huita
Remove the comment. Comments are banned to be in dev

2021-09-24 09:04 UTC, zefirlover commented on server/StudySharp.ApplicationServices/Queries/GetTheoryBlockByIdQuery.cs
> +            CancellationToken cancellationToken)
It's better to write that in one row

2021-09-24 16:32 UTC, zefirlover commented on server/StudySharp.ApplicationServices/Commands/AddTheoryBlockCommand.cs
> +            if (await _context.TheoryBlocks.AnyAsync(c => Equals(c.Name.ToLower(), request.Name.ToLower()) && c.CourseId == request.CourseId, cancellationToken))
Change "c" to "_"

2021-09-24 16:53 UTC, zefirlover commented on server/StudySharp.ApplicationServices/Commands/AddCourseCommand.cs
> +            }, cancellationToken);
Change it to the previous variant
And do the same at the AddTheoryBlockCommand

2021-09-25 10:19 UTC, SleepyF0X approved these changes

2021-09-25 17:59 UTC, KolaCation approved these changes

2021-09-25 18:01 UTC, merged